### ISSUE TITLE
Dataset Download is broken

### ISSUE THREAD

**Issue by antnrueh** [iilab/openoil#62]
after accepting the license terms and clicking on "download" (left sidebar), nothing happens

**Comment by jmatsushita** [comment]
Still not working when registering. Investigating...

**Comment by jmatsushita** [comment]
Fixed.

**Comment by antnrueh** [comment]
Unfortunately still not working for me (on Chrome, and for both cases: accepting license, and not accepting)

**Comment by jmatsushita** [comment]
Have you cleared your cache?

**Comment by antnrueh** [comment]
it was of course the cache... sorry :)
